### ISSUE TITLE
spelling and grammar correction in .md files 😉

### ISSUE THREAD

**Issue by blockspacer** [blockspacer/CXTPL#45]
When creating a great application we generally do small mistakes like spelling mistakes. Try to find out some of our mistakes and we will merge your pull request.

Make sure your text editor is set to remove trailing whitespace.

**Comment by BosEriko** [comment]
Can I take this one?

**Comment by blockspacer** [comment]
> Can I take this one?

Yes, you are welcome

**Comment by BosEriko** [comment]
Hello. Something weird is happening when trying to fork the repo. I wonder if GitHub is down?
![image](https://user-images.githubusercontent.com/10940193/66029968-eaaf6700-e532-11e9-9019-18b62e6319f3.png)

**Comment by blockspacer** [comment]
> Hello. Something weird is happening when trying to fork the repo. I wonder if GitHub is down?
> ![image](https://user-images.githubusercontent.com/10940193/66029968-eaaf6700-e532-11e9-9019-18b62e6319f3.png)

Yes, GitHub is down. I hope GitHub will be fixed soon

**Comment by BosEriko** [comment]
@blockspacer hello! I made a PR. :)

**Comment by blockspacer** [comment]
@BosEriko Thank you a lot!

**Comment by TunnyTraffic** [comment]
Hello, I've made some edits in in CXTPL/README.md, I'll compare against @BosEriko before I PR though.

There is a dead link for the freeCodeCamp icon on line 317 `[![freeCodeCamp](imgs/freecodecamp.png)](https://www.freecodecamp.org/example)`

Also there's only holding text in readmes in the following locations - happy to edit once you've got some text in there to describe the function/usage:

CXTPL/tool/
CXTPL/examples/simple/
CXTPL/examples/cmake_integration/
