### ISSUE TITLE
Code review 😉

### ISSUE THREAD

**Issue by blockspacer** [blockspacer/CXTPL#47]
Code review wanted. Feel free to make pull requests or come with feedback.

Critical issues:
* remove unused code
* remove commented out code
* no codestyle - need to decide about codestyle
* no unit tests

Related to refactoring https://github.com/blockspacer/CXTPL/issues/7

**Comment by madduci** [comment]
Hi, 
I suggest you to use `clang-format` (which is available in Linux, Mac and also Windows), you can add it as a step for CMake if you desire, or run it separately.

There is a online tool to make your own format (https://clangformat.com/) but you can also start from a default one, like LLVM, Microsoft or Google one.
It integrates nicely with some IDEs (e.g. Visual Studio Code/Codium).

The alternative is to use EditorConfig, which is also largely supproted (https://editorconfig.org/)

**Comment by madduci** [comment]
About project, 
I would suggest to bring `conan` as dependency manager, dealing with Boost, GTest, Folly and use some static analytic tool like `cppcheck` or `PVS Studio for open source` to see what kind of problems could be there.

I don't see also where you set compiler flags. I would suggest using `-Wall -Wextra` for gcc or /W4 for Visual Studio, if you want to support it in future

**Comment by blockspacer** [comment]
@madduci Thanks, i`ll try to add that tools.

**Comment by madduci** [comment]
@blockspacer if you add separated issues, I can help you fix them.

A nice-to-have thing is also a docker image to build your code in CI/CD Fashion, with the bonus that you can use Travis-CI or any similar system.

**Comment by blockspacer** [comment]
@madduci I have issue with conan. Maybe you can suggest how to solve it or where to ask. Issue: I use patched version of folly. 

So i need to say to conan `clone folly commit with some hash and apply git patch above it`. Is it possible with conan?

**Comment by madduci** [comment]
yes, definitively. If you know which git hash and patch you need, then it's possible, in a cross-platform fashion too.

**Comment by blockspacer** [comment]
@madduci 
added 
* clang-format
* EditorConfig
* conan

What do you think about current [.clang-format](https://github.com/blockspacer/CXTPL/blob/master/.clang-format), is it usable?

Now i'm stuck with MSAN sanitizer https://github.com/blockspacer/CXTPL/issues/3
MSAN requires to `Build libc++ and libc++abi with MemorySanitizer` as in https://github.com/google/sanitizers/wiki/MemorySanitizerBootstrappingClang#build-libc-and-libcabi-with-memorysanitizer
Is it good idea to create separate dockerfile for sanitizers like MSAN?

Also i plan to use CXCMake_Sanitizers from CXCMake https://github.com/blockspacer/CXCMake/blob/master/cmake/core/sanitize/CXCMake_Sanitizers.cmake

**Comment by madduci** [comment]
hi, sorry for the late reply. Yes, the .clang-format is good and for sanitizers, you can use the same dockerfile

**Comment by blockspacer** [comment]
@madduci Thanks, i`ll try to use same dockerfile for sanitizers
