### ISSUE TITLE
remove unused c++ includes

### ISSUE THREAD

**Issue by blockspacer** [blockspacer/CXTPL#63]
Some files contain #includes that are never used.

- Remove unused includes
- Remove unused functions/variables

**Comment by jakosimov** [comment]
I'll try to fix this right away

**Comment by jakosimov** [comment]
I'm having trouble with updating the submodules.
When i run `git submodule update --force --recursive --init --remote` I end up with the error
```
fatal: Needed a single revision
Unable to find current origin/master revision in submodule path 'third_party/chromium/third_party/skia/third_party/externals/harfbuzz'
```

Has anyone encountered this problem before?

**Comment by blockspacer** [comment]
@Eruvarn 

Thanks for response.

Submodule url for harfbuzz is broken
https://github.com/blockspacer/CXTPL/blob/2db9d4d0bed19c2b0b9831db4eb22f91a455ad73/.gitmodules#L73

It must be https://github.com/harfbuzz/harfbuzz.git

Similar issue may be with submodule url of compact_enc_det

I`ll try to fix submodule url as soon as possible.
